exit status: 0

stdout = """
let f1 : Bool -> Int = fun(b : ?1) => match b {
    true => 1,
    false => 2,
};
let f2 : Bool -> Int = fun(b : ?4) => match b {
    true => 1,
    false => 2,
};
let f2 : Bool -> Int = fun(b : ?4) => match b {
    true => 1,
    false => 2,
};
let f4 : Int -> Bool = fun(n : ?10) => match n {
    1 => false,
    _ => true,
};

"""

stderr = """
warning: Unreachable match case
  ┌─ test-data/elab/match/unreachable.pion:4:5
  │
4 │     true => 3,
  │     ^^^^

warning: Unreachable match case
   ┌─ test-data/elab/match/unreachable.pion:11:5
   │
11 │     false => 3,
   │     ^^^^^

warning: Unreachable match case
   ┌─ test-data/elab/match/unreachable.pion:18:5
   │
18 │     _ => 4,
   │     ^

warning: Unreachable match case
   ┌─ test-data/elab/match/unreachable.pion:25:5
   │
25 │     _ => true,
   │     ^


"""
